name: energy_monitoring_app
description: A new Flutter project

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter_svg: ^1.0.3
  google_fonts: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true


